services:
  individuyelection:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: individuyelection
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    networks:
      - individuy_network
    depends_on:
      - individuydb
    command: >
      bash -lc "
        git config --global --add safe.directory /var/www/html &&
        composer install --optimize-autoloader &&
        php artisan migrate --force &&

        if [ ! -f storage/.seeded ]; then
          php artisan db:seed && touch storage/.seeded;
        fi &&

        php artisan app:calculate-all-ranking-averages &&
        exec php-fpm
      "

  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue_worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    networks:
      - individuy_network
    depends_on:
      - individuydb
    command: >
      bash -lc "
        php artisan queue:work --sleep=3 --tries=3 --verbose
      "

  nginx:
    image: nginx:latest
    container_name: individuy_nginx
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - individuy_network
    depends_on:
      - individuyelection

  individuydb:
    image: mariadb:latest
    container_name: individuydb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: individuyitalianilaravel
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - individuy_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: individuyphpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: individuydb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - individuy_network
    depends_on:
      - individuydb

networks:
  individuy_network:

volumes:
  db_data:
  vendor_data:
  storage_data:
  cache_data:
